export const CABA_BARRIOS = [
  'Agronomía',
  'Almagro',
  'Balvanera',
  'Barracas',
  'Belgrano',
  'Boedo',
  'Caballito',
  'Chacarita',
  'Coghlan',
  'Colegiales',
  'Constitución',
  'Flores',
  'Floresta',
  'La Boca',
  'La Paternal',
  'Liniers',
  'Mataderos',
  'Monte Castro',
  'Montserrat',
  'Nueva Pompeya',
  'Núñez',
  'Palermo',
  'Parque Avellaneda',
  'Parque Chacabuco',
  'Parque Chas',
  'Parque Patricios',
  'Puerto Madero',
  'Recoleta',
  'Retiro',
  'Saavedra',
  'San Cristóbal',
  'San Nicolás',
  'San Telmo',
  'Vélez Sársfield',
  'Versalles',
  'Villa Crespo',
  'Villa del Parque',
  'Villa Devoto',
  'Villa General Mitre',
  'Villa Lugano',
  'Villa Luro',
  'Villa Ortúzar',
  'Villa Pueyrredón',
  'Villa Real',
  'Villa Riachuelo',
  'Villa Santa Rita',
  'Villa Soldati',
  'Villa Urquiza',
] as const

export type CabaBarrio = (typeof CABA_BARRIOS)[number]

export interface ComunaInfo {
  comuna: number
  barrios: CabaBarrio[]
}

export const CABA_COMUNAS: ComunaInfo[] = [
  { comuna: 1, barrios: ['Retiro', 'San Nicolás', 'Puerto Madero', 'San Telmo', 'Montserrat', 'Constitución'] },
  { comuna: 2, barrios: ['Recoleta'] },
  { comuna: 3, barrios: ['Balvanera', 'San Cristóbal'] },
  { comuna: 4, barrios: ['La Boca', 'Barracas', 'Parque Patricios', 'Nueva Pompeya'] },
  { comuna: 5, barrios: ['Almagro', 'Boedo'] },
  { comuna: 6, barrios: ['Caballito'] },
  { comuna: 7, barrios: ['Flores', 'Parque Chacabuco'] },
  { comuna: 8, barrios: ['Villa Soldati', 'Villa Riachuelo', 'Villa Lugano'] },
  { comuna: 9, barrios: ['Liniers', 'Mataderos', 'Parque Avellaneda'] },
  { comuna: 10, barrios: ['Villa Real', 'Monte Castro', 'Versalles', 'Floresta', 'Vélez Sársfield', 'Villa Luro'] },
  { comuna: 11, barrios: ['Villa General Mitre', 'Villa Devoto', 'Villa del Parque', 'Villa Santa Rita'] },
  { comuna: 12, barrios: ['Coghlan', 'Saavedra', 'Villa Urquiza', 'Villa Pueyrredón'] },
  { comuna: 13, barrios: ['Núñez', 'Belgrano', 'Colegiales'] },
  { comuna: 14, barrios: ['Palermo'] },
  { comuna: 15, barrios: ['Chacarita', 'Villa Crespo', 'La Paternal', 'Villa Ortúzar', 'Agronomía', 'Parque Chas'] },
]
